name: Deploy portfolio
run-name: Deploying portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Create env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install Dependencies
        run: npm ci
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}
      - name: Build app
        run: npm run build
      - name: Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./public_html/
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            $host
            $host/random-of-the-day
          budgetPath: ./lighthouse-budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          host: https://iamjustinlee.com
