name: Deploy portfolio
run-name: Deploying portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy-via-FTP:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Create env
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        echo "${{ secrets.GCLOUD_CREDENTIALS_JSON }}" > gcloud-credentials.json
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}
    - name: Install Dependencies
      run: npm ci
    - name: Build app
      run: npm run build
    - name: Sync folders and files to the server
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /out
        server-dir: /public_html